from arcade.key import LEFT, RIGHT

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_TITLE = "LogLine"
FPS = 60

PLAYER_WIDTH = 40
PLAYER_HEIGHT = 90
PLAYER_SPEED = 6
PLAYER_COLOR = (40, 40, 48)

KEY_LEFT = LEFT
KEY_RIGHT = RIGHT
